name: NYC Coverage Report
description: Comments a pull request with the code coverage
author: Nicolás Tinte
branding:
  icon: more-horizontal
  color: gray-dark
inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true
  REPORTER:
    description: Reporter to use
    required: false
  COVERAGE_FOLDER:
    description: Folder where the coverage is
    required: false
  SKIP_COVERAGE_FOLDER:
    description: Whether to use `-t` flag when running the nyc command
    required: false
runs:
  using: node12
  main: dist/index.js
